#!/usr/bin/env python3
"""
Environment Setup Script for Imtehaan AI EdTech Platform Backend
This script helps you set up environment variables for Railway deployment
"""

import os
import sys

def create_env_file():
    """Create .env file from template"""
    
    print("🔧 Setting up environment variables for Imtehaan AI EdTech Platform")
    print("=" * 60)
    
    # Check if .env already exists
    if os.path.exists('.env'):
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (y/N): ").lower()
        if response != 'y':
            print("❌ Setup cancelled.")
            return
    
    # Get OpenAI API key
    print("\n📝 Enter your OpenAI API key:")
    print("   Get it from: https://platform.openai.com/api-keys")
    openai_key = input("   OPENAI_API_KEY: ").strip()
    
    if not openai_key or not openai_key.startswith('sk-'):
        print("⚠️  Warning: OpenAI API key should start with 'sk-'")
        response = input("Continue anyway? (y/N): ").lower()
        if response != 'y':
            print("❌ Setup cancelled.")
            return
    
    # Get LangSmith API key (optional)
    print("\n📝 Enter your LangSmith API key (optional, press Enter to skip):")
    print("   Get it from: https://smith.langchain.com/")
    langsmith_key = input("   LANGSMITH_API_KEY: ").strip()
    
    # Create .env file
    env_content = f"""# Environment Variables for Imtehaan AI EdTech Platform Backend
# Generated by setup-env.py

# OpenAI API Configuration
OPENAI_API_KEY={openai_key}

# LangSmith Configuration (Optional - for AI tracing)
LANGSMITH_API_KEY={langsmith_key or 'your-langsmith-api-key-here'}
LANGSMITH_PROJECT=imtehaan-ai-tutor

# Backend Configuration
HOST=0.0.0.0
PORT=8000

# Environment
RAILWAY_ENVIRONMENT=production
"""
    
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        print("\n✅ .env file created successfully!")
        print("📁 Location: .env")
        print("\n🚀 Next steps:")
        print("1. Commit and push to GitHub:")
        print("   git add .env")
        print("   git commit -m 'Add environment variables'")
        print("   git push origin main")
        print("\n2. Railway will automatically redeploy with the new environment variables")
        print("\n3. Test your backend:")
        print("   https://your-app.railway.app/health")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")

if __name__ == "__main__":
    create_env_file()
